{% set name = "ipywidgets" %}
{% set version = "8.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0005a77a47d77889cafed892b58e33b4a2a96712154404c6548ec22272811ea

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ipython >=6.1.0
    - ipykernel >=4.5.1
    - traitlets >=4.3.1
    - widgetsnbextension >=4.0.4,<5.0.0
    - jupyterlab_widgets >=3.0.4,<4.0.0

test:
  imports:
    - ipywidgets
  requires:
    - jsonschema
    - pip
    - pytest
    - pytz
  commands:
    - pip check
    - pytest -vv --pyargs ipywidgets 

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  dev_url: https://github.com/ipython/ipywidgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
