{% set version = "5.0.0" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  fn: ipywidgets-{{ version }}.tar.gz
  url: https://github.com/ipython/ipywidgets/archive/v{{ version }}.tar.gz
  sha256: 0eb192bc2b33a5ab1adfcf5dd120b876630149d6b930ea43b3ff68299a3f8d81

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - ipython >=4.0.0
    - ipykernel
    - traitlets
    - notebook
    - widgetsnbextension

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  summary: IPython Static Widgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
