{% set version = "7.6.3" %}
{% set sha256 = "9f1a43e620530f9e570e4a493677d25f08310118d315b00e25a18f12913c41f0" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipython >=4.0.0
    - ipykernel >=4.5.1
    - traitlets >=4.3.1,<6.0.0
    - nbformat >=4.2.0
    - widgetsnbextension >=3.5.0,<3.6.0
    - jupyterlab_widgets >=1.0.0

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
