{% set name = "ipywidgets" %}
{% set version = "8.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 870e43b1a35656a80c18c9503bbf2d16802db1cb487eec6fab27d683381dde17

build:
  number: 0
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - comm >=0.1.3
    - ipython >=6.1.0
    - traitlets >=4.3.1
    - widgetsnbextension >=4.0.12,<4.1.0
    - jupyterlab_widgets >=3.0.12,<3.1.0

test:
  imports:
    - ipywidgets
  requires:
    - jsonschema
    - ipykernel
    - pip
    - pytest
    - pytz
  commands:
    - pip check
    - pytest -vv --pyargs ipywidgets 

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Interactive Widgets for the Jupyter Notebook
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipywidgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
