{% set version = "5.1.2" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  fn: ipywidgets-{{ version }}.tar.gz
  url: https://github.com/ipython/ipywidgets/archive/{{ version }}.tar.gz
  sha256: bdd8a4e6736e1240ce20a975f838c1f9a5cd044df733657d354af53267ab21df

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
  run:
    - python
    - ipython >=4.0.0
    - ipykernel
    - traitlets
    - notebook
    - widgetsnbextension

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  summary: IPython Static Widgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
