{% set name = "ipywidgets" %}
{% set version = "8.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0b9b41e49bae926a866e613a39b0f0097745d2b9f1f3dd406641b4a57ec42c9

build:
  number: 0
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - comm >=0.1.3
    - ipython >=6.1.0
    - traitlets >=4.3.1
    - widgetsnbextension >=4.0.10,<4.1
    - jupyterlab_widgets >=3.0.10,<3.1

test:
  imports:
    - ipywidgets
  requires:
    - jsonschema
    - ipykernel
    - pip
    - pytest
    - pytz
  commands:
    - pip check
    - pytest -vv --pyargs ipywidgets 

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Interactive Widgets for the Jupyter Notebook
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipywidgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
