{% set version = "5.1.4" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  fn: ipywidgets-{{ version }}.tar.gz
  url: https://github.com/ipython/ipywidgets/archive/{{ version }}.tar.gz
  sha256: 88bc74564fe36c8f95c49bf83c43fbaf392dd92c9992bdb55f91af2b89ddffdc

build:
  number: 2
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
  run:
    - python
    - ipython >=4.0.0
    - ipykernel >=4.2.2
    - traitlets >=4.2.1
    - widgetsnbextension >=1.2.2

test:
  imports:
    - ipywidgets

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD 3-clause
  summary: Widgets for the Jupyter Notebook

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
