{% set version = "7.8.1" %}
{% set sha256 = "050b87bb9ac11641859af4c36cdb639ca072fb5e121f0f1a401f8a80f9fa008d" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true # [py<36 or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ipython >=4.0.0
    - comm >=0.1.3
    - traitlets >=4.3.1
    - widgetsnbextension >=3.6.6,<3.7.0
    - jupyterlab_widgets >=1.0.0,<3
    - ipython_genutils >=0.2.0,<0.3.0

test:
  imports:
    - ipywidgets
  requires:
    - pip
    - python
  commands:
    - pip check

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io
  dev_url: https://github.com/ipython/ipywidgets
  dev_url: https://github.com/ipython/ipywidgets

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
