travis:
  secure:
    BINSTAR_TOKEN: KvyzgRETCPzPhSbkvzirUjmCe06qRL71OmUdwkRpJ35BjTa/VpBmYGqJQ1lgSP3x8wtv+cCPjvyU/Kl3/VoKZzCowIP2vxGozzffDSDTsj4wYQey/AEt0+ukfH9ORu/Qo43RWVsZT/ODLfshZkBs2JRKqfHTsqJN5w8hurf4BhZsI7gkWrJ9sdqY8Q813Rux23J9J7rEaPzVmX0J50B2ICvqtxgiWWw2gznxThmRrnch9lbkfRYV6lcaOHroQAx2wYQXIVz0OOuEzBvZoohnMATT3y3PRivTwHkGywYGAvtaBhhmsM4nOwWFmiq8GOEL6tfJRWTAo5Qul/gjwiug/l3ROfEx+xI1bjBCtKczbbOIvXDPexxs8z84ATF2a1iU63mSBWXpe8EdchoOdDEC4UBwSFXzTJTUfmHeXeB6uTa8xKYW56Lhjl2pmPQ+g4a6f7ks+aVX97YuLvdJYxkZPGbYGF6nRE43bscD7AWaoc5R/gpoxpsBDVjAiXfMUiZUuDbxG6Ye5BwhJeJHYQyi6dC0ysXnqrU43SJMbX0ZrdlFf/rl828NOzhhPuPhgqOLKKwFdi5HMbTp4bOaLOEefz3sE8MYRCM9Xhvf0HcQNyUTSwUFCcaySZk9jRmGvAxHCwCfOWTh41ZZvcFIe3/LQKPjbUUq/pPyVtkRop2DMWM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
